# Generated by Django 4.2.11 on 2026-05-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('route_date', models.DateField(db_index=True, verbose_name='Sevkiyat Tarihi')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Yolda'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], db_index=True, default='PLANNED', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotalar',
                'db_table': 'routes',
                'ordering': ['-route_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plaka')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kapasite (kg)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'db_table': 'vehicles',
                'unique_together': {('tenant', 'plate_number')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(default=0, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('LOADED', 'Yüklendi'), ('IN_TRANSIT', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('RETURNED', 'İade')], db_index=True, default='PENDING', max_length=20)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Teslim Alan')),
                ('recipient_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('delivery_notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.route')),
            ],
            options={
                'verbose_name': 'Sevkiyat',
                'verbose_name_plural': 'Sevkiyatlar',
                'db_table': 'shipments',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='logistics.vehicle'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['tenant', 'route_date', 'status'], name='routes_tenant__f85889_idx'),
        ),
    ]
