services:
  - type: web
    name: mehmedoglucigk-fte
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health/
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: mehmedoglucigk-fte.onrender.com,.onrender.com
      - key: CORS_ORIGINS
        value: https://frontend-black-psi-97.vercel.app,http://localhost:3000,https://localhost
      - key: CSRF_TRUSTED_ORIGINS
        value: https://frontend-black-psi-97.vercel.app
