# Generated by Django 4.2.11 on 2026-05-12 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('slug', models.SlugField(unique=True)),
                ('tax_office', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(max_length=20, unique=True, verbose_name='Vergi No')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subscription_start', models.DateField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('efatura_username', models.CharField(blank=True, max_length=100)),
                ('efatura_password', models.CharField(blank=True, max_length=255)),
                ('efatura_provider', models.CharField(default='parasut', max_length=50)),
            ],
            options={
                'verbose_name': 'Müşteri Firma',
                'verbose_name_plural': 'Müşteri Firmalar',
                'db_table': 'tenants',
            },
        ),
    ]
