# Generated by Django 4.2.11 on 2026-05-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', "GİB'e Gönderilecek"), ('SENT', "GİB'e Gönderildi"), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], db_index=True, default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ara Toplam')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='KDV')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('gib_uuid', models.CharField(blank=True, max_length=100, verbose_name='GİB UUID')),
                ('gib_response', models.JSONField(blank=True, null=True, verbose_name='GİB Yanıtı')),
                ('gib_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.dealer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='CariAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'Fatura'), ('PAYMENT', 'Tahsilat'), ('RETURN', 'İade'), ('ADJUSTMENT', 'Düzeltme')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cari_transactions', to='accounts.dealer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_entries', to='finance.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_entries', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_transactions', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
                'db_table': 'cari_accounts',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status', 'invoice_date'], name='invoices_tenant__c321bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['dealer', 'status'], name='invoices_dealer__9b034f_idx'),
        ),
        migrations.AddIndex(
            model_name='cariaccount',
            index=models.Index(fields=['tenant', 'dealer', 'transaction_date'], name='cari_accoun_tenant__c58e47_idx'),
        ),
        migrations.AddIndex(
            model_name='cariaccount',
            index=models.Index(fields=['dealer', 'transaction_type'], name='cari_accoun_dealer__bf3737_idx'),
        ),
    ]
