# Generated by Django 4.2.11 on 2026-05-12 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Bayi Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Bayi Adı')),
                ('tax_office', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Vergi No')),
                ('address', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kredi Limiti')),
                ('payment_term_days', models.IntegerField(default=30, verbose_name='Vade Günü')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İskonto Oranı %')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Bayi',
                'verbose_name_plural': 'Bayiler',
                'db_table': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Süper Admin'), ('ADMIN', 'Merkez Admin'), ('DEALER', 'Bayi'), ('STAFF', 'Personel')], db_index=True, default='DEALER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('dealer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='accounts.dealer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['tenant', 'is_active'], name='dealers_tenant__a8c9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['tenant', 'code'], name='dealers_tenant__3a1789_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealer',
            unique_together={('tenant', 'code')},
        ),
    ]
