# Generated by Django 4.2.11 on 2026-06-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, default='', verbose_name='FCM Cihaz Token'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='İletişim E-postası'),
        ),
    ]
