# Generated by Django 4.2.11 on 2026-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('PREPARING', 'Hazırlanıyor'), ('ON_THE_WAY', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
