# Generated by Django 4.2.11 on 2026-05-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('code', models.CharField(max_length=20, verbose_name='Kategori Kodu')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('unit', models.CharField(default='ADET', max_length=20, verbose_name='Birim')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Temel Fiyat')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı %')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stok Miktarı')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Min Stok')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Özel Fiyat')),
                ('valid_from', models.DateField(verbose_name='Geçerlilik Başlangıç')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitiş')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='accounts.dealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Bayi Özel Fiyat',
                'verbose_name_plural': 'Bayi Özel Fiyatlar',
                'db_table': 'dealer_prices',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='products_tenant__76cb13_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'code'], name='products_tenant__606534_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='dealerprice',
            index=models.Index(fields=['dealer', 'product', 'valid_from'], name='dealer_pric_dealer__bbd10e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealerprice',
            unique_together={('dealer', 'product', 'valid_from')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'code')},
        ),
    ]
