# Generated by Django 4.2.11 on 2026-06-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Grup Adı')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu Mu')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Çoklu Seçim')),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün Opsiyon Grubu',
                'verbose_name_plural': 'Ürün Opsiyon Grupları',
                'db_table': 'product_option_groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Seçenek Adı')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat Farkı')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productoptiongroup')),
            ],
            options={
                'verbose_name': 'Ürün Opsiyon Seçeneği',
                'verbose_name_plural': 'Ürün Opsiyon Seçenekleri',
                'db_table': 'product_option_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
